# Generated by Django 4.2.9
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(
                    choices=[
                        ('PENDIENTE', 'Pendiente'),
                        ('PAGADO', 'Pagado'),
                        ('PROCESANDO', 'Procesando'),
                        ('ENVIADO', 'Enviado'),
                        ('ENTREGADO', 'Entregado'),
                        ('CANCELADO', 'Cancelado'),
                        ('REEMBOLSADO', 'Reembolsado'),
                    ],
                    default='PENDIENTE',
                    max_length=20,
                    verbose_name='Estado'
                )),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal (Q)')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento (%)')),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuento (Q)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total (Q)')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe Payment Intent ID')),
                ('stripe_client_secret', models.CharField(blank=True, max_length=500, null=True, verbose_name='Stripe Client Secret')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pedido')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='pedidos',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Cliente'
                )),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(
                    validators=[django.core.validators.MinValueValidator(1)],
                    verbose_name='Cantidad'
                )),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario (Q al momento de compra)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal (Q)')),
                ('pedido', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='detalles',
                    to='pedidos.pedido',
                    verbose_name='Pedido'
                )),
                ('producto', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='detalles_pedido',
                    to='productos.producto',
                    verbose_name='Producto'
                )),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
                'db_table': 'detalle_pedidos',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', 'estado'], name='pedidos_usuario_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pedido'], name='pedidos_fecha_idx'),
        ),
    ]
